import itertools,json
import numpy as np,polars as pl,torch,joblib
import session72_action_list as s
from session12_compare import compare
def main():
 d,a,x,groups,T,V,M,D,fv,bid,pos,amax=s.pack();N,n=M.shape;sub=d['subtype'].to_numpy();hfv=d['fold'].to_numpy();g=a['row'].to_numpy();active=a['players_active'].to_numpy();saved=pl.read_parquet(s.ROOT/'isolation_oof.parquet');errors=[];checks=[]
 for f in range(4):
  model=joblib.load(s.ROOT/f'action_list_fold{f}.joblib');levels=[int(np.unique(amax[(hfv!=f)&(sub==k)])[0]) for k in [1,2]];assert levels==model['levels'];support=np.isin(active,levels);rows=g[support];rb=bid[rows];rp=pos[rows];head=(active[support]==levels[1]).astype(int);indices=torch.tensor((rb*n+rp)*2+head);A=torch.tensor(s.infer(model,x[support]));np.testing.assert_array_equal(A.numpy(),s.infer(model,x[support][::-1])[::-1]);z=s.hand_logits(A,indices,N,n);p=torch.softmax(torch.cat([torch.zeros_like(z[:,:,:1]),z],2),2).numpy();train=torch.tensor(np.flatnonzero(fv!=f));rt=torch.tensor(fv[rb]!=f);rb=torch.tensor(rb);K=torch.full((N,),model['minimum']);want=s.objective(A,indices,N,n,T,V,M,D,train,K,rt,rb);TT=T.clone();VV=V.clone();DD=D.clone();TT[fv==f]=0;VV[fv==f]=False;DD[fv==f]=999;got=s.objective(A,indices,N,n,TT,VV,M,DD,train,K,rt,rb);assert want==got
  for i in np.flatnonzero(fv==f):
   q=groups[i];want=q.select('pair_id','hand_id').join(saved,on=['pair_id','hand_id'],validate='1:1',maintain_order='left');v=p[i,:len(q),1:];errors.append(float(abs(v-want.select('event_primary','event_secondary').to_numpy()).max()));np.testing.assert_array_equal(s.conditioned(v,model['minimum']),want['list_inclusion'].to_numpy())
  checks.append({'fold':f,'outer_target_mutation_exact':True,'action_permutation_exact':True})
                                                                        
 probs=np.array([.2,.4,.3,.1]);expect=np.zeros(3)
 for v in itertools.product([0,1],repeat=4):
  prob=np.prod(np.where(v,probs,1-probs));category=1 if any(v[:2]) else 2 if any(v[2:]) else 0;expect[category]+=prob
 z=s.hand_logits(torch.tensor(np.log(probs/(1-probs))),torch.tensor([0,0,1,1]),1,1);actual=torch.softmax(torch.cat([torch.zeros_like(z[:,:,:1]),z],2),2).numpy()[0,0];np.testing.assert_allclose(actual,expect,atol=1e-12)
                                                                            
                                                                                
 base=pl.read_parquet('artifacts/evidence_session64_equal_list_pressure/oof.parquet').select('pair_id','hand_id',pl.col('equal').alias('r33'),'pressure59','full');raw=pl.concat([pl.read_parquet(f'artifacts/evidence_session10/nested6/nested_outer{f}.parquet').filter(pl.col('fold')==f).select('pair_id','hand_id','base') for f in range(4)]);out=base.join(saved,on=['pair_id','hand_id'],how='left',validate='1:1').join(raw,on=['pair_id','hand_id'],validate='1:1').with_columns(pl.when(pl.col('list_inclusion').is_not_null()).then(.25*pl.col('base')+.25*pl.col('raw_inclusion')+.5*pl.col('list_inclusion')).otherwise(pl.col('pressure59')).alias('action_list'));out=out.with_columns(((pl.col('action_list')+pl.col('full'))*.5).alias('action_list_r33_recipe'));old=pl.read_parquet(s.ROOT/'oof.parquet');delta=float(out.select('pair_id','hand_id','action_list').join(old.select('pair_id','hand_id',pl.col('action_list').alias('old')),on=['pair_id','hand_id'],validate='1:1').select((pl.col('action_list')-pl.col('old')).abs().max()).item());out.write_parquet(s.ROOT/'oof.parquet');names=['r33','action_list','action_list_r33_recipe'];r,_=compare(s.ROOT/'oof.parquet',names,'action_list');report={'method':s.__doc__,'config':s.CONFIG,'results':{k:{'MAP':r[k].mean(),'folds':r.group_by('fold').agg(pl.col(k).mean()).sort('fold')[k].to_list(),'families':dict(r.group_by('family').agg(pl.col(k).mean()).iter_rows())} for k in names}};(s.ROOT/'report.json').write_text(json.dumps(report,indent=2));assert max(errors)==0;proof={'models_replayed':4,'event_probability_error':max(errors),'conditioning_replay_exact':True,'checks':checks,'enumerated_action_paths':16,'aggregation_probability_error':float(abs(actual-expect).max()),'outer_fold_base_refresh_score_change':delta};(s.ROOT/'verification.json').write_text(json.dumps(proof,indent=2));print(json.dumps(proof,indent=2))
if __name__=='__main__':main()
