import json
import numpy as np,polars as pl
import session74_complete_rescore as s
from session9_pair_baseline import assemble,SEQ
C=pl.col
def main():
 raw,aggregate,sourcehash=s.shared_code();acts,sizes,models=s.models();folds=json.load(open(s.P/'table_folds.json'));cols=json.load(open(s.P/'feature_columns.json'));pcols=json.load(open(s.P/'residual_columns.json'));known=pl.concat([pl.read_csv('data/development_labels.csv').select('pair_id','player_1','player_2'),pl.read_csv('data/evaluation_pairs.csv').select('pair_id','player_1','player_2')]);meta=pl.concat([pl.read_parquet(p,columns=['pair_id','table_id','phase']).filter(C('phase')=='development').drop('phase') for p in sorted((s.P/'pair_features').glob('*.parquet'))]);checks=[];modelerr=0
 for w in ['full','first_2000','last_2000']:
  q=pl.read_parquet(f'artifacts/pair_session73_exclusion_audit/{w}.parquet').join(meta,on='pair_id',validate='1:1');ex={v:s.exclusions(q,v) for v in ['r4s','r4k']};outputs={v:pl.read_parquet(s.ROOT/f'{v}_{w}.parquet') for v in ex};ids=pl.concat([z.select('pair_id') for z in ex.values()]).unique();eligible=q.join(ids,on='pair_id',how='semi')['table_id'].unique().sort().to_list();tables=[next(t for t in eligible if folds[t]==f) for f in range(4)]
  for table in tables:
   local=q.filter(C('table_id')==table);ns={'pl':pl,'np':np,'C':C,'root':s.P,'path':s.P/'actions'/f'{table}.parquet','window':None if w=='full' else w,'window_actions':s.window_actions,'cols':cols,'folds':folds,'table':table,'models':acts,'sizes':sizes,'known':known,'HANDS_ALL':None};exec(raw,ns);h=ns['h'].filter(C('phase')=='development').with_columns(pl.selectors.float().cast(pl.Float32));del ns;roster={hid:set(z['player_id']) for (hid,),z in pl.read_parquet(s.P/'states'/f'{table}.parquet',columns=['hand_id','player_id']).unique().group_by('hand_id')}
   for v in ex:
    e=ex[v].join(local.select('pair_id'),on='pair_id',how='semi');em={pid:set(z['qx']) for (pid,),z in e.group_by('pair_id')};hh=h.filter(C('pair_id').is_in(pl.Series(list(em),dtype=pl.String).implode()));keep=np.array([not bool(roster[hid]&em[pid]) for pid,hid in hh.select('pair_id','hand_id').iter_rows()],dtype=bool);kept=hh.filter(pl.Series(keep));counts=kept.group_by('pair_id').len().rename({'len':'kept_replay'});frame=aggregate(kept);pr=np.mean([m.predict_proba(frame.select(pcols).to_numpy(),thread_count=2) for m in models[v,folds[table]]],0) if len(frame) else np.zeros((0,4));replay=e.select('pair_id').unique().join(counts,on='pair_id',how='left').join(frame.select('pair_id').with_columns(pl.Series('new_replay',1-pr[:,0])),on='pair_id',how='left').with_columns(C('kept_replay').fill_null(0)).with_columns(pl.when(C('kept_replay')<10).then(0).otherwise(C('new_replay')).alias('new_replay'));z=replay.join(outputs[v],on='pair_id',validate='1:1');assert (z['kept_replay']==z['n_kept']).all();err=float((z['new_replay']-z['risk_new']).abs().max() or 0);modelerr=max(modelerr,err);assert err<1e-12;checks.append({'window':w,'table':table,'fold':folds[table],'model':v,'pairs_replayed':len(z),'kept_count_exact':True,'score_error':err})
  for v in ex:
   out=outputs[v];ids=ex[v].select('pair_id').unique();assert len(out.join(ids,on='pair_id',how='semi'))==len(ids);unchanged=out.join(ids,on='pair_id',how='anti');np.testing.assert_allclose(unchanged['risk_orig'].to_numpy(),1-unchanged['none'].to_numpy(),atol=1e-15,rtol=0)
 seq={v:pl.read_csv(f'artifacts/{v}/eval_all_lpo.csv') for v in SEQ};ev=assemble(pl.read_csv('artifacts/candidate_r12/eval_r4s_all.csv'),pl.read_csv('artifacts/candidate_r12/eval_r4k_all.csv'),seq).join(pl.read_csv('artifacts/candidate_r33/submission.csv').select('pair_id',C('risk_score').alias('r33')),on='pair_id',validate='1:1');error=float((ev['risk_score']-ev['r33']).abs().max());assert error<1e-12
 report={'raw_source_sha256':sourcehash,'sampled_raw_exclusion_replays':checks,'maximum_model_score_error':modelerr,'all_candidates_covered_in_all_six_runs':True,'noncandidate_risks_unchanged':True,'r33_evaluation_risk_recipe_error':error,'evaluation_submission_changed':False};(s.ROOT/'verification.json').write_text(json.dumps(report,indent=2));print(json.dumps(report,indent=2))
if __name__=='__main__':main()
