import json
import numpy as np,polars as pl
from catboost import CatBoostClassifier
import session80_soft_passivity as s
C=pl.col
def main():
 full,d,a,ac=s.data();x,names,raw=s.features(d,a,ac);np.testing.assert_array_equal(x,np.load(s.ROOT/'features.npz')['x']);xm,_,_=s.features(d.with_columns(pl.lit(0).alias('evidence'),pl.lit(0).alias('subtype'),pl.lit(-999).alias('evidence_rank')),a,ac);np.testing.assert_array_equal(x,xm);labs=pl.read_csv('data/development_labels.csv').select('pair_id','player_1','player_2');count=0
 for (table,),q in d.group_by('table_id'):
  query=q.select('pair_id','hand_id').join(labs,on='pair_id',validate='m:1');mapping=pl.concat([query.select('pair_id','hand_id',C('player_1').alias('player_id'),C('player_2').alias('partner')),query.select('pair_id','hand_id',C('player_2').alias('player_id'),C('player_1').alias('partner'))]);raw=pl.read_parquet(f'artifacts/policy/actions/{table}.parquet').join(mapping,on=['hand_id','player_id']);st=pl.read_parquet(f'artifacts/policy/states/{table}.parquet').select('hand_id',C('street_no').cast(pl.Float32),C('player_id').alias('partner'),'fold_no');raw=raw.join(st,on=['hand_id','street_no','partner'],validate='m:1');expected=raw.filter((C('fold_no')>=C('action_no'))&(((C('action_class')==2)&(C('last_aggressor')==C('partner')))|((C('action_class')==1)&(C('players_active')==2))));keys=['pair_id','hand_id','street_no','action_no'];cached=a.join(q.select('pair_id','hand_id'),on=['pair_id','hand_id'],how='semi');assert set(expected.select(keys).iter_rows())==set(cached.select(keys).iter_rows());count+=len(expected)
 cfg=json.load(open(s.ROOT/'columns.json'));xx=np.column_stack([d.select(cfg['hand']).to_numpy(),x]);fv=d['fold'].to_numpy();saved=d.select('pair_id','hand_id').join(pl.read_parquet(s.ROOT/'event_oof.parquet'),on=['pair_id','hand_id'],validate='1:1',maintain_order='left');err=0
 for f in range(4):
  m=CatBoostClassifier();m.load_model(str(s.ROOT/f'secondary_fold{f}.cbm'));p=m.predict_proba(xx[fv==f],thread_count=2)[:,1];err=max(err,float(abs(p-saved['bg_secondary'].to_numpy()[fv==f]).max()));np.testing.assert_array_equal(p,m.predict_proba(xx[fv==f][::-1],thread_count=2)[:,1][::-1])
 assert err==0;z=pl.read_parquet(s.ROOT/'event_oof.parquet').join(pl.read_parquet('artifacts/evidence_session59_pressure_equity/event_oof.parquet'),on=['pair_id','hand_id'],suffix='_base',validate='1:1');np.testing.assert_array_equal(z['bg_primary'].to_numpy(),z['bg_primary_base'].to_numpy());other=z.filter(~C('pair_id').is_in(d['pair_id'].unique().implode()));np.testing.assert_array_equal(other['bg_secondary'].to_numpy(),other['bg_secondary_base'].to_numpy());proof={'models_replayed':4,'score_error':err,'actions_verified_complete_against_raw_policy':count,'feature_replay_exact':True,'feature_label_mutation_exact':True,'row_permutation_exact':True,'other_heads_unchanged':True,'added_features':len(names)};(s.ROOT/'verification.json').write_text(json.dumps(proof,indent=2));print(json.dumps(proof,indent=2))
if __name__=='__main__':main()
